
enum ErrorCodes {
  REQUEST_ENTITY_TOO_LARGE = "REQUEST_ENTITY_TOO_LARGE",
  REQUEST_ENTITY_SIZE_MISMATCH = "REQUEST_ENTITY_SIZE_MISMATCH",
  REQUEST_STREAM_ABORTED = "REQUEST_STREAM_ABORTED",
}

export default ErrorCodes;